# copts = [
#     "-Wno-unused-parameter",
#     "-Wno-shadow",
#     "-Wno-implicit-fallthrough",
#     "-Wno-cast-function-type",
# ]

# linkopts = [
#     "-framework GLUT",
#     "-framework OpenGL",
# ]

cc_binary(
    name = "mesh_align",
    srcs = ["mesh_align.cc"],
    deps = [
        "//include:main",
        "//libsrc:libtrimesh",
    ],
)

cc_binary(
    name = "mesh_cat",
    srcs = ["mesh_cat.cc"],
    deps = [
        "//include:main",
        "//libsrc:libtrimesh",
    ],
)

cc_binary(
    name = "mesh_cc",
    srcs = ["mesh_cc.cc"],
    deps = [
        "//include:main",
        "//libsrc:libtrimesh",
    ],
)

cc_binary(
    name = "mesh_crunch",
    srcs = ["mesh_crunch.cc"],
    deps = [
        "//include:main",
        "//libsrc:libtrimesh",
    ],
)
